Hw01 is compiletd
breadrock1/otus-golang pull request #1
Opened 2023-10-09 18:31 UTC by breadrock1

2023-10-10 05:36 UTC, ityulkanov requested changes

2023-10-10 05:36 UTC, ityulkanov commented on hw01_hello_otus/go.mod
>  module github.com/fixme_my_friend/hw01_hello_otus
Поправьте, пожалуйста путь к модулю, и приму

2023-10-23 18:25 UTC, breadrock1 commented on hw01_hello_otus/go.mod
>  module github.com/fixme_my_friend/hw01_hello_otus
Fixed misprint. Please review fresh changes)

2023-10-24 12:10 UTC, ityulkanov commented on hw01_hello_otus/go.mod
> +module github.com/otus-golang/hw01_hello_otus
![image](https://github.com/breadrock1/otus-golang/assets/998653/da7098e4-ff07-4630-9974-959dce79eabd)
Пока не находит такого

2024-01-03 15:06 UTC, ityulkanov approved these changes

2024-01-08 12:51 UTC, breadrock1 commented on hw01_hello_otus/go.mod
> +module github.com/otus-golang/hw01_hello_otus
Поправил!

2024-02-19 19:33 UTC, merged