Hw04 is Completed
breadrock1/otus-golang pull request #3
Opened 2024-01-04 11:57 UTC by breadrock1

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [x] Пайплайн зелёный - 4 балла
- [x] Добавлены новые юнит-тесты для списка - 1 балл
- [x] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [x] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-01-08 08:04 UTC, ityulkanov requested changes
Глеб, почистите пожалуйста pr от лишних файлов, и нужно поправить немного логику связанную с переполнением очереди.

2024-01-08 08:04 UTC, engineer-go commented on hw02_unpack_string/unpack.go
Вот это тут лишнее

2024-01-08 08:04 UTC, engineer-go commented on hw02_unpack_string/unpack_test.go
тоже

2024-01-08 08:04 UTC, engineer-go commented on hw03_frequency_analysis/top.go
и это

2024-01-08 08:04 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +		delete(l.items, key)
так вы удаляете тот элемент, который вы только что добавили, а не removable элемент, поправьте пожалуйста. Вам нужен key removable элемента

2024-01-08 12:39 UTC, breadrock1 commented on hw02_unpack_string/unpack.go
Поправил

2024-01-08 12:39 UTC, breadrock1 commented on hw02_unpack_string/unpack_test.go
Поправил

2024-01-08 12:40 UTC, breadrock1 commented on hw03_frequency_analysis/top.go
Поправил!

Как только зальются Hw02 и Hw03, сделаю rebase/cherry, дабы почистить историю.

2024-02-24 11:56 UTC, breadrock1 commented on hw04_lru_cache/cache.go
> +		delete(l.items, key)
Йеп! Поправил

2024-03-28 13:33 UTC, ityulkanov approved these changes

2024-04-02 20:48 UTC, merged