Hw03 is Completed
breadrock1/otus-golang pull request #8
Opened 2024-01-07 21:20 UTC by breadrock1

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-01-08 08:17 UTC, engineer-go requested changes
Удалите пожалуйста лишние файлы, и приму. Ну и подкинул заодно пару комментариев как можно было бы упростить сортировку полученной мапы

2024-01-08 08:17 UTC, engineer-go commented on hw02_unpack_string/unpack.go
Удалите пожалуйста файл предыдущего задания из PR

2024-01-08 08:17 UTC, engineer-go commented on hw02_unpack_string/unpack_test.go
и этот тоже

2024-01-08 08:17 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		}
```suggestion
		toWordsMap[word]++
```

2024-01-08 08:17 UTC, engineer-go commented on hw03_frequency_analysis/top.go
> +	groupKeys := getSortedKeys(groupedByFreq)
Вот тут мы можем всё сделать одним вызовом sort(i,j). Получаем только слова (wordsSlice), и с помощью sort.Slice(wordsSlice , func(i, j) -> {
a, b := wordsSlice[i], wordsSlice[j] .. } сортируем  через wordsFreq

2024-01-08 08:51 UTC, breadrock1 commented on hw03_frequency_analysis/top.go
> +		}
Уточни, пожалуйста, почему так нужно сделать?! 

Я не инкрементирую значение ключа в блоке `else`, потому что производится запись в мапу с новым ключом и значением (по умолчанию 1). Зачем мне еще раз это инкрементировать во вне `if/else`?!

2024-01-08 12:41 UTC, breadrock1 commented on hw02_unpack_string/unpack.go
Поправил!

2024-01-08 12:41 UTC, breadrock1 commented on hw02_unpack_string/unpack_test.go
Поправил! 

Как только зальётся Hw02, сделаю rebase/cherry, дабы почистить историю.

2024-01-10 14:02 UTC, breadrock1 commented on hw03_frequency_analysis/top.go
> +	groupKeys := getSortedKeys(groupedByFreq)
Гораздо меньше кода стало! Спасибо)

2024-02-26 07:48 UTC, ityulkanov approved these changes

2024-02-26 07:48 UTC, ityulkanov commented on hw02_unpack_string/go.mod
> +module github.com/fixme_my_friend/hw02_unpack_string
А зачем вы сменили путь к модулю, было же правильно?

2024-02-26 08:16 UTC, ityulkanov approved these changes

2024-02-26 10:18 UTC, merged